# Generated by Django 2.2.5 on 2019-09-23 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Name of Bond e.g. 750 or 200 etc', max_length=255, unique=True)),
                ('first_prize', models.CharField(help_text='First prize in Rs.', max_length=255)),
                ('second_prize', models.CharField(help_text='Second prize in Rs.', max_length=255)),
                ('third_prize', models.CharField(help_text='Third prize in Rs.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bond100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, help_text='Year of prize bond announced')),
                ('date', models.DateField(default=datetime.date.today)),
                ('bond_number', models.IntegerField(default=0, help_text='Prize bond number')),
                ('bond_level', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('bond_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbm_bonds.BondCategory')),
            ],
        ),
    ]
