# Generated by Django 2.2.5 on 2019-09-24 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbm_bonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondDrawDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, help_text='Year of prize bond announced')),
                ('date', models.DateField(default=datetime.date.today)),
                ('bond_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbm_bonds.BondCategory')),
            ],
        ),
    ]
